// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Data} from '../models';

export function GetCurrentWorkers():Promise<Array<Data.WorkerInfo>>;

export function Greet(arg1:string):Promise<string>;
